### ISSUE TITLE
proposal: Automatically register resource service providers

### ISSUE THREAD

**Issue by pmccarren** [esbenp/distributed-laravel#11]

**Comment by esbenp** [comment]
I like the idea- it is something that has been considered before. Tbh., I do not think we should do it. I think a big part of what people like about Larapi is that is not too distant from normal Laravel. Most of the conceptual things are the same. I try not to add too much "framework magic". It might add to the confusion of "where to register tings". Imagine you are a newcomer and some library tells you to register the service provider in `config/app.php`, however Larapi also has a mechanism for registering Service Providers - which one to use? Which is resolved first? etc. etc. It can create a lot of questions that might not be obvious and so forth.

**Comment by pmccarren** [comment]
You raise a very good point! I do agree, there is value in not adding too much "framework magic" as that quickly increases the learning curve while also making other things more annoying to debug!

Plus, in all honesty, it's not like we're talking about *that* much work to include the ServiceProviders in the app/config.php!

Perhaps there is an alternative approach: esbenp/larapi#32? (tracked in new issue as I'm closing this one)
