### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ardanirohman** [esbenp/distributed-laravel#3]
hi @esbenp  i very interest with your concept distributed-laravel,
can you give some example to use it?
thanks

**Comment by nikolajlovenhardt** [comment]
Hello @ardanirohman 

https://github.com/esbenp/larapi is an example on how to use it.

I would recommend that you read this blog post: http://esbenp.github.io/2016/04/11/modern-rest-api-laravel-part-1/
